services:
  traccar:
    image: traccar/traccar:latest
    ports:
      - 25002:5013
      - 25003:5023
    volumes:
      - ${TRACCAR_DATA}/traccar/logs:/opt/traccar/logs
      - ${TRACCAR_DATA}/traccar/traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - ${TRACCAR_DATA}/traccar/data:/opt/traccar/data/:rw
    networks:
      - dokploy-network
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  dokploy-network:
    external: true
