services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: tuckfow-home
    dns:
      - 1.1.1.1
      - 1.1.0.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - dokploy-network
      - pihole-cf-tunnel
    environment:
      TZ: "Europe/Madrid"
      FTLCONF_dns_listeningMode: all
      FTLCONF_webserver_api_password: ${PIHOLE_WEB_PASSWORD}
    volumes:
      - ${PIHOLE_DATA}/etc/pihole:/etc/pihole
      - ${PIHOLE_DATA}/etc/dnsmasq.d:/etc/dnsmasq.d
    labels:
      - homepage.group=Management
      - homepage.name=Pi-hole (main)
      - homepage.icon=pi-hole.png
      - homepage.href=https://${PIHOLE_LOCAL_DOMAIN}
      - homepage.description=DNS, DHCP management
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

  pihole-cf-tunnel:
    image: cloudflare/cloudflared
    container_name: pihole-cf-tunnel
    restart: unless-stopped
    command: tunnel run
    networks:
      - dokploy-network
      - pihole-cf-tunnel
    dns:
      - 1.1.1.1
      - 1.1.0.0
    environment: 
      - TUNNEL_TOKEN=${PIHOLE_CLOUDFLARE_TUNNEL_TOKEN}

networks:
  dokploy-network:
    external: true
  pihole-cf-tunnel:
    external: true
