services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    hostname: speedtest
    restart: unless-stopped
    networks:
      - cloudflare-exposed
    volumes:
      - ${SPEEDTEST_DATA}/speedtest/config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=Monitoring / Stats
      - homepage.name=Speedtest
      - homepage.icon=librespeed.png
      - homepage.href=https://${SPEEDTEST_LOCAL_DOMAIN}
      - homepage.description=Speedtest tracker
      - homepage.widget.type=speedtest
      - homepage.widget.url=http://speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_KEY=${SPEEDTEST_APP_KEY}
      - APP_NAME=${SPEEDTEST_APP_NAME}
      - APP_URL=${SPEEDTEST_DOMAIN}
      - APP_TIMEZONE=Europe/Madrid
      - DISPLAY_TIMEZONE=Europe/Madrid
      - PUBLIC_DASHBOARD=true
      - SPEEDTEST_SCHEDULE="0 * * * *"
      - PRUNE_RESULTS_OLDER_THAN=90
      - TELEGRAM_BOT_TOKEN=${SPEEDTEST_TELEGRAM_BOT_TOKEN}

networks:
  cloudflare-exposed:
    external: true
