services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - cloudflare-exposed
    dns:
      - 1.1.1.1
      - 1.0.0.1
    dns_search: .
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  cloudflare-exposed:
    driver: bridge
    name: cloudflare-exposed