services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    security_opt:
      - no-new-privileges:true
    dns:
      - 1.1.1.1
      - 1.0.0.1
    dns_search: .
    networks:
      - cloudflare-exposed
      - dokploy-network
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  cloudflare-exposed:
    driver: bridge
    name: cloudflare-exposed
