name: Lint Markdown

on:
  pull_request:
    paths:
      - "**/*.md"

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"
